import { GdsIcons, createGdsVocabularyPack } from '@sovereignsquad/gds-core/client';

const savedFeedback = { icon: GdsIcons.Check, color: 'teal', messageId: 'gds.feedback.saved' } as const;
const deletedFeedback = { icon: GdsIcons.Delete, color: 'red', messageId: 'gds.feedback.deleted' } as const;
const openedFeedback = { icon: GdsIcons.Eye, color: 'teal', messageId: 'gds.feedback.opened' } as const;

export const cameraAdminVocabularyPacks = [
  createGdsVocabularyPack('users', {
    promote: { defaultMessage: 'Promote', icon: GdsIcons.Users, feedback: savedFeedback },
    demote: { defaultMessage: 'Demote', icon: GdsIcons.Users, feedback: savedFeedback },
    activate: { defaultMessage: 'Activate', icon: GdsIcons.Check, feedback: savedFeedback },
    deactivate: { defaultMessage: 'Deactivate', icon: GdsIcons.Delete, feedback: deletedFeedback },
    merge: { defaultMessage: 'Merge', icon: GdsIcons.Users, feedback: savedFeedback },
    'merge-confirm': { defaultMessage: 'Merge Users', icon: GdsIcons.Confirm, feedback: savedFeedback },
    'merge-cancel': { defaultMessage: 'Cancel', icon: GdsIcons.Cancel, feedback: openedFeedback },
  }),
  createGdsVocabularyPack('partner-users', {
    'add-access': { defaultMessage: 'Add access', icon: GdsIcons.Add, feedback: savedFeedback },
    activate: { defaultMessage: 'Activate', icon: GdsIcons.Check, feedback: savedFeedback },
    deactivate: { defaultMessage: 'Deactivate', icon: GdsIcons.Delete, feedback: deletedFeedback },
    remove: { defaultMessage: 'Remove', icon: GdsIcons.Delete, feedback: deletedFeedback },
  }),
  createGdsVocabularyPack('tryon', {
    approve: { defaultMessage: 'Approve', icon: GdsIcons.Check, feedback: savedFeedback },
    reject: { defaultMessage: 'Reject', icon: GdsIcons.Delete, feedback: deletedFeedback },
    great: { defaultMessage: 'Great', icon: GdsIcons.Trophy, feedback: savedFeedback },
    'remove-great': { defaultMessage: 'Remove Great', icon: GdsIcons.Delete, feedback: deletedFeedback },
    service: { defaultMessage: 'Service', icon: GdsIcons.Settings, feedback: savedFeedback },
    'retry-job': { defaultMessage: 'Retry job', icon: GdsIcons.Refresh, feedback: savedFeedback },
    'rerun-job': { defaultMessage: 'Rerun job', icon: GdsIcons.Refresh, feedback: savedFeedback },
    'cancel-job': { defaultMessage: 'Cancel job', icon: GdsIcons.Cancel, feedback: deletedFeedback },
    'resend-result': { defaultMessage: 'Resend result', icon: GdsIcons.Send, feedback: savedFeedback },
    'restore-orphaned-result': { defaultMessage: 'Restore prior result', icon: GdsIcons.Refresh, feedback: savedFeedback },
    view: { defaultMessage: 'View', icon: GdsIcons.Eye, feedback: openedFeedback },
    remove: { defaultMessage: 'Remove', icon: GdsIcons.Delete, feedback: deletedFeedback },
    fix: { defaultMessage: 'Fix', icon: GdsIcons.Refresh, feedback: openedFeedback },
    'pin-to-slideshow': { defaultMessage: 'Add to slideshow', icon: GdsIcons.Add, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('tryon-moderation', {
    action: { defaultMessage: 'Moderation action', icon: GdsIcons.Check, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('landing-pages', {
    create: { defaultMessage: 'Create landing page', icon: GdsIcons.Add, feedback: savedFeedback },
    edit: { defaultMessage: 'Edit landing page', icon: GdsIcons.Edit, feedback: savedFeedback },
    delete: { defaultMessage: 'Delete landing page', icon: GdsIcons.Delete, feedback: deletedFeedback },
    open: { defaultMessage: 'Open landing page', icon: GdsIcons.Eye, feedback: openedFeedback },
    'copy-url': { defaultMessage: 'Copy URL', icon: GdsIcons.Copy, feedback: savedFeedback },
    'editor-action': { defaultMessage: 'Landing page action', icon: GdsIcons.Edit, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('slideshows', {
    create: { defaultMessage: 'Create slideshow', icon: GdsIcons.Add, feedback: savedFeedback },
    edit: { defaultMessage: 'Edit slideshow', icon: GdsIcons.Edit, feedback: savedFeedback },
    delete: { defaultMessage: 'Delete slideshow', icon: GdsIcons.Delete, feedback: deletedFeedback },
    open: { defaultMessage: 'Open slideshow', icon: GdsIcons.Eye, feedback: openedFeedback },
    'copy-url': { defaultMessage: 'Copy URL', icon: GdsIcons.Copy, feedback: savedFeedback },
    'editor-action': { defaultMessage: 'Slideshow action', icon: GdsIcons.Edit, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('slideshow-layouts', {
    create: { defaultMessage: 'Create layout', icon: GdsIcons.Add, feedback: savedFeedback },
    edit: { defaultMessage: 'Edit layout', icon: GdsIcons.Edit, feedback: savedFeedback },
    delete: { defaultMessage: 'Delete layout', icon: GdsIcons.Delete, feedback: deletedFeedback },
    open: { defaultMessage: 'Open layout', icon: GdsIcons.Eye, feedback: openedFeedback },
    'copy-url': { defaultMessage: 'Copy URL', icon: GdsIcons.Copy, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('event-gallery', {
    'upload-images': { defaultMessage: 'Upload images', icon: GdsIcons.Upload, feedback: savedFeedback },
    'upload-folder': { defaultMessage: 'Upload folder', icon: GdsIcons.Upload, feedback: savedFeedback },
    'clear-finished': { defaultMessage: 'Clear finished', icon: GdsIcons.Clear, feedback: savedFeedback },
    'start-capturing': { defaultMessage: 'Start capturing', icon: GdsIcons.Capture, feedback: openedFeedback },
    'toggle-select-all': { defaultMessage: 'Toggle selection', icon: GdsIcons.Toggle, feedback: savedFeedback },
    'confirm-bulk-remove': { defaultMessage: 'Remove selected', icon: GdsIcons.Delete, feedback: deletedFeedback },
    'cancel-bulk-remove': { defaultMessage: 'Cancel remove', icon: GdsIcons.Cancel, feedback: openedFeedback },
    'start-bulk-remove': { defaultMessage: 'Start remove', icon: GdsIcons.Delete, feedback: openedFeedback },
    'view-submission': { defaultMessage: 'View submission', icon: GdsIcons.Eye, feedback: openedFeedback },
    'download-submission': { defaultMessage: 'Download submission', icon: GdsIcons.Download, feedback: savedFeedback },
    'confirm-remove': { defaultMessage: 'Remove', icon: GdsIcons.Delete, feedback: deletedFeedback },
    'cancel-remove': { defaultMessage: 'Cancel', icon: GdsIcons.Cancel, feedback: openedFeedback },
    'start-remove': { defaultMessage: 'Start remove', icon: GdsIcons.Delete, feedback: openedFeedback },
  }),
  createGdsVocabularyPack('style-sections', {
    'edit-colors': { defaultMessage: 'Edit colors', icon: GdsIcons.Edit, feedback: openedFeedback },
    'manage-frames': { defaultMessage: 'Manage frames', icon: GdsIcons.Gallery, feedback: openedFeedback },
    'assign-frames': { defaultMessage: 'Assign frames', icon: GdsIcons.Add, feedback: savedFeedback },
    'manage-frame-assignments': { defaultMessage: 'Manage frame assignments', icon: GdsIcons.Settings, feedback: openedFeedback },
    'manage-logos': { defaultMessage: 'Manage logos', icon: GdsIcons.Gallery, feedback: openedFeedback },
    'assign-logos': { defaultMessage: 'Assign logos', icon: GdsIcons.Add, feedback: savedFeedback },
    'manage-logo-assignments': { defaultMessage: 'Manage logo assignments', icon: GdsIcons.Settings, feedback: openedFeedback },
  }),
  createGdsVocabularyPack('custom-pages', {
    'save-all': { defaultMessage: 'Save all', icon: GdsIcons.Save, feedback: savedFeedback },
    'move-up': { defaultMessage: 'Move up', icon: GdsIcons.TrendingUp, feedback: savedFeedback },
    'move-down': { defaultMessage: 'Move down', icon: GdsIcons.TrendingDown, feedback: savedFeedback },
    edit: { defaultMessage: 'Edit', icon: GdsIcons.Edit, feedback: savedFeedback },
    delete: { defaultMessage: 'Delete', icon: GdsIcons.Delete, feedback: deletedFeedback },
    'add-who-are-you': { defaultMessage: 'Add identity page', icon: GdsIcons.Add, feedback: savedFeedback },
    'add-accept': { defaultMessage: 'Add accept page', icon: GdsIcons.Add, feedback: savedFeedback },
    'add-cta': { defaultMessage: 'Add CTA page', icon: GdsIcons.Add, feedback: savedFeedback },
    'add-restart': { defaultMessage: 'Add restart page', icon: GdsIcons.Add, feedback: savedFeedback },
    'save-page': { defaultMessage: 'Save page', icon: GdsIcons.Save, feedback: savedFeedback },
    'cancel-page': { defaultMessage: 'Cancel page', icon: GdsIcons.Cancel, feedback: openedFeedback },
  }),
  createGdsVocabularyPack('events', {
    'form-action': { defaultMessage: 'Event action', icon: GdsIcons.Edit, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('logos', {
    'back-to-list': { defaultMessage: 'Back to logos', icon: GdsIcons.Back, feedback: openedFeedback },
    save: { defaultMessage: 'Save logo', icon: GdsIcons.Save, feedback: savedFeedback },
    'cancel-edit': { defaultMessage: 'Cancel edit', icon: GdsIcons.Cancel, feedback: openedFeedback },
    delete: { defaultMessage: 'Delete logo', icon: GdsIcons.Delete, feedback: deletedFeedback },
    'remove-upload': { defaultMessage: 'Remove upload', icon: GdsIcons.Delete, feedback: deletedFeedback },
    'cancel-create': { defaultMessage: 'Cancel create', icon: GdsIcons.Cancel, feedback: openedFeedback },
    create: { defaultMessage: 'Create logo', icon: GdsIcons.Add, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('partners', {
    save: { defaultMessage: 'Save partner', icon: GdsIcons.Save, feedback: savedFeedback },
    'cancel-edit': { defaultMessage: 'Cancel edit', icon: GdsIcons.Cancel, feedback: openedFeedback },
    create: { defaultMessage: 'Create partner', icon: GdsIcons.Add, feedback: savedFeedback },
    'cancel-create': { defaultMessage: 'Cancel create', icon: GdsIcons.Cancel, feedback: openedFeedback },
  }),
  createGdsVocabularyPack('event-frames', {
    toggle: { defaultMessage: 'Toggle frame', icon: GdsIcons.Toggle, feedback: savedFeedback },
    remove: { defaultMessage: 'Remove frame', icon: GdsIcons.Delete, feedback: deletedFeedback },
    assign: { defaultMessage: 'Assign frame', icon: GdsIcons.Add, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('partner-frames', {
    'save-defaults': { defaultMessage: 'Save defaults', icon: GdsIcons.Save, feedback: savedFeedback },
    cancel: { defaultMessage: 'Cancel', icon: GdsIcons.Cancel, feedback: openedFeedback },
  }),
  createGdsVocabularyPack('event-logos', {
    toggle: { defaultMessage: 'Toggle logo', icon: GdsIcons.Toggle, feedback: savedFeedback },
    remove: { defaultMessage: 'Remove logo', icon: GdsIcons.Delete, feedback: deletedFeedback },
    assign: { defaultMessage: 'Assign logo', icon: GdsIcons.Add, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('partner-logos', {
    'save-defaults': { defaultMessage: 'Save defaults', icon: GdsIcons.Save, feedback: savedFeedback },
    cancel: { defaultMessage: 'Cancel', icon: GdsIcons.Cancel, feedback: openedFeedback },
  }),
  createGdsVocabularyPack('garments', {
    'remove-upload': { defaultMessage: 'Remove upload', icon: GdsIcons.Delete, feedback: deletedFeedback },
    create: { defaultMessage: 'Create garment', icon: GdsIcons.Add, feedback: savedFeedback },
    'cancel-create': { defaultMessage: 'Cancel create', icon: GdsIcons.Cancel, feedback: openedFeedback },
    'back-to-list': { defaultMessage: 'Back to garments', icon: GdsIcons.Back, feedback: openedFeedback },
    save: { defaultMessage: 'Save garment', icon: GdsIcons.Save, feedback: savedFeedback },
    'cancel-edit': { defaultMessage: 'Cancel edit', icon: GdsIcons.Cancel, feedback: openedFeedback },
    delete: { defaultMessage: 'Delete garment', icon: GdsIcons.Delete, feedback: deletedFeedback },
  }),
  createGdsVocabularyPack('tryon-setups', {
    create: { defaultMessage: 'Create setup', icon: GdsIcons.Add, feedback: savedFeedback },
    'cancel-create': { defaultMessage: 'Cancel create', icon: GdsIcons.Cancel, feedback: openedFeedback },
    'back-to-list': { defaultMessage: 'Back to setups', icon: GdsIcons.Back, feedback: openedFeedback },
    save: { defaultMessage: 'Save setup', icon: GdsIcons.Save, feedback: savedFeedback },
    'cancel-edit': { defaultMessage: 'Cancel edit', icon: GdsIcons.Cancel, feedback: openedFeedback },
    duplicate: { defaultMessage: 'Duplicate setup', icon: GdsIcons.Add, feedback: savedFeedback },
    archive: { defaultMessage: 'Archive setup', icon: GdsIcons.Delete, feedback: deletedFeedback },
    unarchive: { defaultMessage: 'Unarchive setup', icon: GdsIcons.Check, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('card-display-settings', {
    save: { defaultMessage: 'Save', icon: GdsIcons.Save, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('tryon-maintenance', {
    'refresh-worker': { defaultMessage: 'Refresh worker health', icon: GdsIcons.Refresh, feedback: openedFeedback },
    'run-audit': { defaultMessage: 'Run data integrity audit', icon: GdsIcons.Check, feedback: openedFeedback },
    'reconcile-apply': { defaultMessage: 'Apply reconciliation', icon: GdsIcons.Check, feedback: savedFeedback },
  }),
  createGdsVocabularyPack('frames', {
    'remove-upload': { defaultMessage: 'Remove upload', icon: GdsIcons.Delete, feedback: deletedFeedback },
    create: { defaultMessage: 'Create frame', icon: GdsIcons.Add, feedback: savedFeedback },
    'cancel-create': { defaultMessage: 'Cancel create', icon: GdsIcons.Cancel, feedback: openedFeedback },
    'back-to-list': { defaultMessage: 'Back to frames', icon: GdsIcons.Back, feedback: openedFeedback },
    save: { defaultMessage: 'Save frame', icon: GdsIcons.Save, feedback: savedFeedback },
    'cancel-edit': { defaultMessage: 'Cancel edit', icon: GdsIcons.Cancel, feedback: openedFeedback },
    delete: { defaultMessage: 'Delete frame', icon: GdsIcons.Delete, feedback: deletedFeedback },
  }),
];
